version: '3.8'

services:

  sleek-airflow:
    image: sleek-airflow:latest
    container_name: airflow
    depends_on:
      - postgres
    volumes:
      - ./airflow:/opt/airflow
      - ./dags:/opt/airflow/dags  # Mount DAGs folder
    ports:
      - "9090:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow_db
    command: airflow standalone

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
